name: update changelog

on:
  release:
    types: [released]

  workflow_dispatch:

permissions: write-all

jobs:
  update:
    uses: jetstreamlabs/.github/.github/workflows/update-changelog.yml@main
